name: audioplayers
description: A flutter plugin to play multiple audio files simultaneously
version: 0.14.0
homepage: https://github.com/luanpotter/audioplayer

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin
      macos:
        pluginClass: AudioplayersPlugin
      web:
        pluginClass: AudioplayersPlugin
        fileName: audioplayers_web.dart

dependencies:
  uuid: # 2.0.4 - DONE: Secure code reviewed diff 1b7db8f (2.0.1) 981adca (2.0.4)
    git: 
      url: git://github.com/KomodoPlatform/dart-uuid.git
      ref: 981adcac181443e3def4ced76a43b96c534e68ce
  path_provider: ^1.5.1 # flutter.dev
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0+3 # dart.dev
  test: ^1.9.4 # dart.dev

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
